plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/workspace/landlord-h-site/public/public"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]